#include "/Engine/Private/Common.ush"

int numParticles;
float instanceSize;

RWStructuredBuffer<float4> positions;
RWStructuredBuffer<float4> positions_other;

[numthreads(256, 1, 1)]
void copyPositions(uint3 ThreadId : SV_DispatchThreadID)
{
    int index = ThreadId.x;

    if (index >= numParticles)
        return;
    
    positions_other[index] = positions[index];
    positions_other[index].w = instanceSize;
}